import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-gallery',
  templateUrl: './gallery.component.html',
  styleUrls: ['./gallery.component.scss']
})
export class GalleryComponent implements OnInit {
  ServrUrl = ['assets/images_mall/DSC_0091.JPG',
  'assets/images_mall/DSC_0092.JPG',
  'assets/images_mall/DSC_0093.JPG',
  'assets/images_mall/DSC_0094.JPG',
  'assets/images_mall/DSC_0095.JPG',
  'assets/images_mall/DSC_0096.JPG',
  'assets/images_mall/DSC_0097.JPG',
 
  'assets/images_mall/DSC_0099.JPG',
  'assets/images_mall/DSC_0100.JPG',
  'assets/images_mall/DSC_0101.JPG',
  'assets/images_mall/DSC_0102.JPG',
  'assets/images_mall/DSC_0103.JPG',
  'assets/images_mall/DSC_0104.JPG',
  'assets/images_mall/DSC_0105.JPG',
  'assets/images_mall/DSC_0106.JPG',
  'assets/images_mall/DSC_0107.JPG',
  'assets/images_mall/DSC_0108.JPG',
  'assets/images_mall/DSC_0109.JPG',
  'assets/images_mall/DSC_0110.JPG',
  'assets/images_mall/DSC_0111.JPG',
  'assets/images_mall/DSC_0112.JPG',
  'assets/images_mall/DSC_0115.JPG',
  'assets/images_mall/DSC_0114.JPG',
  'assets/images_mall/DSC_0115.JPG',
  'assets/images_mall/DSC_0116.JPG',
  'assets/images_mall/DSC_0121.JPG',
  'assets/images_mall/DSC_0123.JPG',
  'assets/images_mall/DSC_0124.JPG',
  'assets/images_mall/DSC_0125.JPG',
  'assets/images_mall/DSC_0126.JPG',
  'assets/images_mall/DSC_0127.JPG',
  'assets/images_mall/DSC_0128.JPG',
  'assets/images_mall/DSC_0129.JPG',
  'assets/images_mall/DSC_0130.JPG',
  'assets/images_mall/DSC_0131.JPG',
  'assets/images_mall/DSC_0132.JPG',
  'assets/images_mall/DSC_0133.JPG',
  'assets/images_mall/DSC_0134.JPG',
  'assets/images_mall/DSC_0135.JPG',
  'assets/images_mall/DSC_0136.JPG',
  'assets/images_mall/DSC_0137.JPG',
  'assets/images_mall/DSC_0138.JPG',
  'assets/images_mall/DSC_0139.JPG',
  'assets/images_mall/DSC_0140.JPG',
  'assets/images_mall/DSC_0141.JPG',
  'assets/images_mall/DSC_0142.JPG',
  'assets/images_mall/DSC_0143.JPG',
  'assets/images_mall/DSC_0144.JPG',
  'assets/images_mall/DSC_0145.JPG',
  'assets/images_mall/DSC_0146.JPG',
  'assets/images_mall/DSC_0147.JPG',
  'assets/images_mall/DSC_0148.JPG',
  'assets/images_mall/DSC_0149.JPG',
  'assets/images_mall/DSC_0150.JPG',
  'assets/images_mall/DSC_0151.JPG',
  'assets/images_mall/DSC_0152.JPG',
  'assets/images_mall/DSC_0153.JPG',
  'assets/images_mall/DSC_0154.JPG',
  'assets/images_mall/DSC_0155.JPG',
  'assets/images_mall/DSC_0156.JPG',
  'assets/images_mall/DSC_0157.JPG',
  'assets/images_mall/DSC_0159.JPG',
  'assets/images_mall/DSC_0160.JPG',
  'assets/images_mall/DSC_0160.JPG',
  'assets/images_mall/DSC_0160.JPG',
  'assets/images_mall/DSC_0161.JPG',
  'assets/images_mall/DSC_0162.JPG',
  'assets/images_mall/DSC_0163.JPG',
  'assets/images_mall/DSC_0164.JPG',
  'assets/images_mall/DSC_0165.JPG',
  'assets/images_mall/DSC_0166.JPG',
  'assets/images_mall/DSC_0167.JPG',
  'assets/images_mall/DSC_0168.JPG',
  'assets/images_mall/DSC_0169.JPG',
  'assets/images_mall/DSC_0170.JPG',
  'assets/images_mall/DSC_0171.JPG',  
  'assets/images_mall/DSC_0173.JPG',
  'assets/images_mall/DSC_0174.JPG',
  'assets/images_mall/DSC_0175.JPG',
  'assets/images_mall/DSC_0176.JPG',
  'assets/images_mall/DSC_0178.JPG',
  'assets/images_mall/DSC_0179.JPG',
  'assets/images_mall/DSC_0180.JPG', 
  'assets/images_mall/DSC_0181.JPG',
  'assets/images_mall/DSC_0182.JPG',  
   'assets/images_mall/DSC_0184.JPG'
]
  constructor() { }

  ngOnInit() {
  }

}
